### ISSUE TITLE
Cannot find module 'ng2-material-dropdown' from '../../node_modules/ngx-chips/fesm2015/ngx-chips.mjs'

### ISSUE THREAD

**Issue by kaknovuy** [Gbuomprisco/ngx-chips#1025]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

```

**Current behavior**
Error during test with jest on angular v13
 ● Test suite failed to run

    Cannot find module 'ng2-material-dropdown' from '../../node_modules/ngx-chips/fesm2015/ngx-chips.mjs'

    Require stack:
      node_modules/ngx-chips/fesm2015/ngx-chips.mjs
      common/ui/custom-tag-input/components/core-custom-tag-input.module.ts
      common/ui/custom-tag-input/public-api.ts
      organizations/use-cases/create-organization/components/core-organization-profile-form/core-organization-profile-form.component.ts
      organizations/use-cases/create-organization/core-create-organization.module.ts
      organizations/public-api.ts
      organizations/use-cases/organizations-list/components/core-organizations-list/core-organizations-list.component.spec.ts

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (../../node_modules/ngx-chips/fesm2015/ngx-chips.mjs:7:23)

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**
Run application tests

**What do you use to build your app?. Please specify the version**

macOS: 10.13.6
Angular CLI: 13.3.1
Node: 14.19.0
Package Manager: npm 6.14.16
OS: darwin x64

**Angular version:** 

@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@angular/cdk                    13.3.2
@angular/material               13.3.2
@schematics/angular             13.3.1
ng-packagr                      13.3.0
rxjs                            6.6.7
typescript                      4.4.4

**ngx-chips version:**
3.0.0

**Comment by srp324** [comment]
Was able to avoid this issue by downgrading to v2.1.0!
