### ISSUE TITLE
Dom Exception when using keyboard to remove first tag

### ISSUE THREAD

**Issue by vadim82** [Gbuomprisco/ngx-chips#352]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

I am using angular material2 beta 3 library. I have a sidebar widget in which I am using the `ng2-tag-input` component.

1. Select the first suggestion. 
2. Then press backspace 2 times. 1st time to select the chip, 2nd time to remove the chip.

I get an error
```
core.es5.js:1084 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (http://localhost:5000/dist/vendor.js:103429:35)
    at WebAnimationsPlayer.init (http://localhost:5000/dist/vendor.js:103412:29)
    at InjectableAnimationEngine.DomAnimationEngine._queuePlayer (http://localhost:5000/dist/vendor.js:102703:16)
    at InjectableAnimationEngine.DomAnimationEngine.animateTransition (http://localhost:5000/dist/vendor.js:102618:14)
    at InjectableAnimationEngine.DomAnimationEngine.setProperty (http://localhost:5000/dist/vendor.js:102489:18)
    at AnimationRenderer.setProperty (http://localhost:5000/dist/vendor.js:90507:26)
    at setElementProperty (http://localhost:5000/dist/vendor.js:9893:19)
    at checkAndUpdateElementValue (http://localhost:5000/dist/vendor.js:9812:13)
    at checkAndUpdateElementInline (http://localhost:5000/dist/vendor.js:9752:24)
    at checkAndUpdateNodeInline (http://localhost:5000/dist/vendor.js:12439:23)
    at checkAndUpdateNode (http://localhost:5000/dist/vendor.js:12414:16)
    at prodCheckAndUpdateNode (http://localhost:5000/dist/vendor.js:12867:5)
    at Object.eval [as updateRenderer] (ng:///Ng2DropdownModule/Ng2DropdownMenu.ngfactory.js:300:5)
    at Object.updateRenderer (http://localhost:5000/dist/vendor.js:12784:70)
    at checkAndUpdateView (http://localhost:5000/dist/vendor.js:12386:14)
```

I am using angular 4. I am using the chrome browser.

**Comment by Gbuomprisco** [comment]
Are there any custom styles applied?

**Comment by vadim82** [comment]
The `tag-input` component is sitting inside the `md-sidenav` component. There are no custom styles applied to the `tag-input` component.

**Comment by vadim82** [comment]
Also note, that this issue only happens when a chip is removed via backspace. If I use the mouse, everything works great.

**Comment by Gbuomprisco** [comment]
@vadim82 does it also happen if the tag-input is not inside md-sidenav? If it doesn't, I am not sure if the issue is in this component.

**Comment by vadim82** [comment]
Fair point. I tried using this component inside an angular-material2 `md-card` component and had the same issues. So it seems like the 2 libraries do not play nice together. Something to do with the animate library. Its possible that it is an angular material issue, but I am only seeing this error in the `ng2-tag-input` component, not in any other ones. So I was just wondering if maybe there is some animation being triggered that is causing this error.

**Comment by Gbuomprisco** [comment]
That error usually occurs when the animated component doesn't have a size pre-defined. I struggle to understand though why this would happen :(

**Comment by vadim82** [comment]
Is there some kind of flag we can set to disable animations? At least that would allow us to continue using this library.

**Comment by Gbuomprisco** [comment]
@vadim82 I haven't found none that would allow me to optionally include animations. I'd suggest you to fork and remove the animations, or maybe extend the component and override the animations

**Comment by meleskim** [comment]
Having exact same issue. Tag-input is not inside an angular material component
