### ISSUE TITLE
Error: formControlName must be used with a parent formGroup directive

### ISSUE THREAD

**Issue by carol-braileanu** [Gbuomprisco/ngx-chips#566]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
When adding ngx-chips to a blank page in my form:
```
<tag-input name="roomRegistration" [onlyFromAutocomplete]="true" [identifyBy]="'id'" [displayBy]="'name'">
    <tag-input-dropdown [appendToBody]="false" [autocompleteItems]="[{ id:'xx', name: 'room1' }]" [identifyBy]="'id'" [displayBy]="'name'"></tag-input-dropdown>
  </tag-input>
```
I get the following error: 

```
Error: formControlName must be used with a parent formGroup directive.  You'll want to add a formGroup
       directive and pass it an existing FormGroup instance (you can create one in your class).

      Example:

      
    <div [formGroup]="myGroup">
      <input formControlName="firstName">
    </div>

    In your class:

    this.myGroup = new FormGroup({
       firstName: new FormControl()
    });
    at Function.t.controlParentException (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at e._checkParentType (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at e._setUpControl (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at e.ngOnChanges (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at kn (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at di (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at ui (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at qi (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at n (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
    at Object.F.ɵvid.n [as updateDirectives] (vendor.f55f65273c3a6d1b10fc.bundle.js:1)
```
After this the application becomes unresponsive. What puzzles me is that it was working a few days back, but it stopped all of a sudden. Also, when I try to add the control to a page outside of a form I get the error: `No provider for e!`

I tried downgrading my angular-cli and node versions and I still get the same behavior. Also tried with ngx-chips 1.4.6 and 1.5.3.

**Expected behavior**
There should be no error

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli@1.4.3

**Angular version:** 
```
@angular/cli: 1.4.2
node: 7.2.0
os: win32 x64
@angular/animations: 4.4.1
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/compiler-cli: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/platform-server: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
typescript: 2.5.2

```

**ngx-chips version:**
1.5.6

**Browser:** [all ]

**Comment by Gbuomprisco** [comment]
Are you using a formGroup like the error says?

**Comment by carol-braileanu** [comment]
No I am not, I use template-driven forms and i don't have formControlName anywhere in my project.

**Comment by Gbuomprisco** [comment]
Then ngModel is required to display the items

**Comment by carol-braileanu** [comment]
Sorry the code I posted was from a test, this is the actual html code that is failing:

```
<tag-input name="equipmentRegistration" [onlyFromAutocomplete]="true" [(ngModel)]="eventEquipments" [identifyBy]="'id'" [displayBy]="'name'">
        <tag-input-dropdown [appendToBody]="false" [autocompleteItems]="equipments" [identifyBy]="'id'" [displayBy]="'name'"></tag-input-dropdown>
      </tag-input>
```

**Comment by Gbuomprisco** [comment]
Your code looks OK now, it's quite possible that an Angular update caused this then

**Comment by carol-braileanu** [comment]
Yes, that is what I suspect. It only happens on the production build, ng serve works fine.
I downgraded my angular-cli version and my typescript version and i got the same error. I haven't tried lowering my angular version, but I would like to avoid that.

**Comment by wizquest-labs** [comment]
I'm having the same issue. Any resolution to this? @Gbuomprisco kindly advise

**Comment by Gbuomprisco** [comment]
Not that I know of

**Comment by carol-braileanu** [comment]
I tried setting a [formGroup] attribute on the main form. But then I got the following error:

```
ERROR Error: No provider for e!
    at D (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at M (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at t._throwOrNull (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at t._getByKeyDefault (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at t._getByKey (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at t.get (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at Ve (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at t.get (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at Pn (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
    at Dn (vendor.9ed6ed6cc35e3fefeac4.bundle.js:1)
zn @ main.4a55185e2cb760a765a9.bundle.js:1
t.logError @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
t.handleError @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
(anonymous) @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
t.invoke @ polyfills.04df92a83810024c8847.bundle.js:1
r.run @ polyfills.04df92a83810024c8847.bundle.js:1
t.runOutsideAngular @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
e.tick @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
(anonymous) @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
t.invoke @ polyfills.04df92a83810024c8847.bundle.js:1
onInvoke @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
t.invoke @ polyfills.04df92a83810024c8847.bundle.js:1
r.run @ polyfills.04df92a83810024c8847.bundle.js:1
t.run @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
next @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
e.object.r @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
T14+.e.__tryOrUnsub @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
T14+.e.next @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
T14+.e._next @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
T14+.e.next @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
e.next @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
e.emit @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
rt @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
onHasTask @ vendor.9ed6ed6cc35e3fefeac4.bundle.js:1
t.hasTask @ polyfills.04df92a83810024c8847.bundle.js:1
t._updateTaskCount @ polyfills.04df92a83810024c8847.bundle.js:1
r._updateTaskCount @ polyfills.04df92a83810024c8847.bundle.js:1
r.runTask @ polyfills.04df92a83810024c8847.bundle.js:1
i @ polyfills.04df92a83810024c8847.bundle.js:1
e.invokeTask @ polyfills.04df92a83810024c8847.bundle.js:1
h @ polyfills.04df92a83810024c8847.bundle.js:1
d @ polyfills.04df92a83810024c8847.bundle.js:1
main.4a55185e2cb760a765a9.bundle.js:1 ERROR CONTEXT 

component:n
componentRenderElement:app-event-detail
context:n
elDef:{index: 11, parent: null, renderParent: null, bindingIndex: 1, outputIndex: 1, …}
elOrCompView:Object
elView:{def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: n, …}
injector:t
nodeDef:{index: 13, parent: {…}, renderParent: {…}, bindingIndex: 8, outputIndex: 3, …}
nodeIndex:13
providerTokens:Array(4)
references:[Exception: TypeError: Cannot read property 'instance' of undefined at Yn (http://localhost:4200/vendor.9ed6ed6cc35e3fefeac4.bundle.js:1:47779) at er (http://localhost:4200/vendor.9ed6ed6cc35e3fefeac4.bundle.js:1:65354) at t.get [as references] (http://localhost:4200/vendor.9ed6ed6cc35e3fefeac4.bundle.js:1:139170) at t.remoteFunction (<anonymous>:2:26)]
renderNode:form
view:
component:n {dialog: t, eventService: n, personService: n, equipmentService: n, globalService: t, …}
context:n {dialog: t, eventService: n, personService: n, equipmentService: n, globalService: t, …}
def:{nodeFlags: 1062194323, rootNodeFlags: 402653203, nodeMatchedQueries: 6, flags: 0, factory: ƒ, …}
disposables:(43) [ƒ, ƒ, ƒ, undefined × 40]
nodes:(231) [{…}, t, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, undefined × 218]
oldValues:(135) [undefined × 135]
parent:{def: {…}, parent: null, viewContainerParent: null, parentNodeDef: null, context: {…}, …}
parentNodeDef:{index: 1, parent: {…}, renderParent: {…}, bindingIndex: 0, outputIndex: 0, …}
renderer:t {delegate: t}
root:
errorHandler:t {_console: console}
injector:t {_constructionCounter: 1, _providers: Array(1), _parent: t, keyIds: Array(1), objs: Array(1)}
ngModule:t {_parent: t, _bootstrapComponents: Array(1), _def: {…}, _destroyListeners: Array(1), _moduleType: ƒ, …}
projectableNodes:[]
renderer:t {delegate: t}
rendererFactory:t {delegate: t}
sanitizer:e {_doc: document}
selectorOrNode:undefined
__proto__:Object
state:13
viewContainerParent:null
__proto__:Object
__proto__:Object
```

**Comment by carol-braileanu** [comment]
@wizquest-labs have you found a workaround for this? I tried forking but I can't get it to compile in my app...

**Comment by carol-braileanu** [comment]
@Gbuomprisco when I try to compile I get a warning: `export 'TagModel' was not found in '../../core'`

Also I get some errors like: `src/ngx-chips/modules/components/tag/tag.componen
t.ts (19,24): Cannot find name 'global'.`

Got any idea what is causing this?

**Comment by Gbuomprisco** [comment]
Sorry but not really.. Looks like typescript complains for something. Maybe try to fix the version as the one in the repository

**Comment by carol-braileanu** [comment]
I found that the issue goes away when you remove the [appendToBody]="false" attribute. However I use it in a popup and I need to use that setting.

**Comment by Elianmtg** [comment]
can you find some solution for this error? At 2021, and i have the same issue.
